site_name: EMBRS
repo_url: https://github.com/AREAL-GT/embrs
docs_dir: docs_raw
site_dir: site
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - content.code.annotate
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
  - autorefs
  - section-index
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
nav:
  - Home: index.md
  - Tutorials:
      - Background: background.md
      - Raw Data: raw_data.md
      - Map Creation: map_creation.md
      - Wind Forecast: wind_forecast.md
      - Running a Simulation: running_sim.md
      - Log Files: log_files.md
      - Visualization: visualization.md
  - User Guide:
      - Custom Control Classes: user_code.md
      - Fire Interface: interface_reference.md
      - Fire Prediction: fire_prediction.md
      - Example Index: example_index.md
  - API Reference:
      - Fire Simulator: sim_documentation.md
      - Base Classes: base_class_documentation.md
      - Models:
          - Rothermel Spread: models_rothermel.md
          - Fuel Models: models_fuel.md
          - Crown Fire: models_crown.md
          - Weather: models_weather.md
          - Wind Forecast: models_wind.md
          - Spotting: models_spotting.md
          - Fuel Moisture: models_moisture.md
      - Tools: tools_documentation.md
      - Utilities: utilities_documentation.md
      - Data Classes: data_classes_documentation.md
      - Exceptions: exceptions_documentation.md
  - Theory and Background:
      - Fire Modelling: fire_modelling.md
      - Interpreting Visualizations: interpreting_visualizations.md
